spring.application.name=SpringSecurity

spring.security.user.name=vishal
spring.security.user.password=vishal

spring.datasource.url = jdbc:postgresql://localhost:5432/SpringSecurityTelusko
spring.datasource.username= postgres
spring.datasource.password= Vishu@894
